# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166U46DQ3fYVxPde_XePVsy174tHym2KG
"""

"""
    Task 1
    - Create a function that searches for all occurrences of a value (find_val) in a given list (lst) and replaces them with another value (replace_val).
    - lst must be a list.
    - Return the modified list.
"""

def find_and_replace(lst, find_val, replace_val):

  for i in range(len(lst)):
    if lst[i] == find_val:
      lst[i] = replace_val
  return lst

# Task 2
# Invoke the function "find_and_replace" using the following scenarios:
# - [1, 2, 3, 4, 2, 2], 2, 5
# - ["apple", "banana", "apple"], "apple", "orange"


numbers = [1, 2, 3, 4, 2, 2]
print(f"Original list: {numbers}")
new_numbers = find_and_replace(numbers, 2, 5)
print(f"Modified list: {new_numbers}")

fruits = ["apple", "banana", "apple"]
print(f"\nOriginal list: {fruits}")
new_fruits = find_and_replace(fruits, "apple", "orange")
print(f"Modified list: {new_fruits}")

