# -*- coding: utf-8 -*-
"""q3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11oa5DgqrlgBLL5XUgxlPLq0LawugoaMx
"""

def update_dictionary(dct, key, value):
    """
    Task 1
    - Create a function that updates a dictionary (dct) with a new key-value pair.
    - If the key already exists in dct, print the original value, then update its value.
    - Return the updated dictionary.
    """

    if key in dct:
        print(f"Key '{key}' already exists. Original value: {dct[key]}")

    dct[key] = value

    return dct # The updated dictionary.

# Task 2
# Invoke the function "update_dictionary" using the following scenarios:
# - {}, "name", "Alice"
# - {"age": 25}, "age", 26

# 1. Add a new key-value pair
person ={}
print(f"Original dict is empty: {person}")
person1 = update_dictionary(person, "name", "Alice")
print(f"Results of adding a new key-value pair,{person1}")

# 2. Update a new value for existing key
person0 ={"age": 25}
print(f"\nOriginal dict: {person0}")
person2 = update_dictionary(person0, "age", 26)
print(f"Results of updating a new value,{person2}")

