# -*- coding: utf-8 -*-
"""q4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J29C0sRlzh06arPDbuDwi3oj1ZoH6ipT
"""

def string_reverse(s):
    """
    Task 1
    - Create a function that reverses a given string (s).
    - s must be a string.
    - Return the reversed string.
    """
    # Check if the input 's' is a string.
    if not isinstance(s, str):
        raise TypeError("Input 's' must be a string.")

    # The most common and idiomatic Python way to reverse a sequence (like a string)
    # is using slicing with a step of -1.
    return s[::-1]


# Task 2
# Invoke the function "string_reverse" using the following scenarios:
# - "Hello World"
# - "Python"

greeting=input("Enter a greeting: ")
print(f"Original 1: {greeting}, Reversed 1: {string_reverse(greeting)}")
greeting=input("\nEnter a greeting: ")
print(f"Original 2: {greeting}, Reversed 2: {string_reverse(greeting)}")

