# -*- coding: utf-8 -*-
"""q5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_fubqv4WBpHsOGWnNB8tIZDjut9w2RP
"""

def check_divisibility(num, divisor):
    """
    Task 1
    - Create a function to check if the number (num) is divisible by another number (divisor).
    - Both num and divisor must be numeric.
    - Return True if num is divisible by divisor, False otherwise.
    """
    # 1. Input Validation: Check if both num and divisor are numeric (int or float)
    if not isinstance(num, (int, float)) :
        raise TypeError("Input 'num' must be a number.")
    if not isinstance(divisor, (int, float)) :
        raise TypeError("Input 'divisor' must be a number.")

    # 2. Check for Zero Divisor
    if divisor == 0:
      raise ZeroDivisionError("Divisor cannot be zero.")

    # 3. Divisibility Check: Use the modulo operator (%)
    divisible = num % divisor
    return divisible == 0
    """
# Task 2
# Invoke the function "check_divisibility" using the following scenarios:
# - 10, 2
# - 7, 3
    """

# Scenario 1: 10, 2
result_1 = check_divisibility(10, 2)
print(f"10 is divisible by 2: {result_1}")

# Scenario 2: 7, 3
result_2 = check_divisibility(7, 3)
print(f"7 is divisible by 3: {result_2}")

