# -*- coding: utf-8 -*-
"""q6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mshVyLhzV5cWomoiDVK7VD4YU1CR_O93
"""

def find_first_negative(lst):
    """
    Task 1
    - Create a function that finds the first negative number in a list (lst).
    - Return the first negative number if found, otherwise return "No negatives".
    - Use a while loop to implement this.
    """
    i=0 # Initialize the index counter

    while i < len(lst):
        if lst[i]  < 0: # Check if the current element is negative (less than zero)
            return lst[i] # Found the first negative number, return it immediately
        i+=1 # Move to the next element

    return "No negatives" # If the loop finishes without finding a negative number, return the default message


# Task 2
# Invoke the function "find_first_negative" using the following scenario:
# - [3, 5, -1, 7, -2, 8]
# - [2, 10, 7, 0]

lst1=[3, 5, -1, 7, -2, 8]
lst2=[2, 10, 7, 0]

print(f"First negative number in list {lst1} is: {find_first_negative(lst1)}.")
print(f"First negative number in list {lst2} is: {find_first_negative(lst2)}.")

