# -*- coding: utf-8 -*-
"""q7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15en8onf-4wiXELd6tNWtI8XiVxMGattD
"""

# Create class
class Car:
    """
    Task 1
    - Define a class named Car with attributes: make, model, year
    - Initialize these attributes in the __init__ method
    - Add a method named describe_car() that prints information about the car as "Year Make Model"
    """
  # Constructor
    def __init__(self, make, model, year):
      self.make = make
      self.model = model
      self.year = year

  # Method
    def describe_car(self):
      return f"{self.year} {self.make} {self.model}"


# Task 2
# Create an instance of the Car class with the following attributes and call describe_car method:
# - Make: Toyota, Model: Corolla, Year: 2020

# Init care object
my_car = Car(make="Toyota", model="Corolla", year="2020")

# Call describe_car method
print("Car Description:")
print(my_car.describe_car())

